services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: career-ai-frontend
    restart: always
    environment:
      # MUST use your secure HTTPS domain now!
      - VITE_API_BASE_URL=https://career.gridsphere.in
    ports:
      - "5173:5173"